[profile.default]
retries = 0
test-threads = "num-cpus"
status-level = "all"
final-status-level = "flaky"

[profile.ci]
retries = 2
test-threads = 4
status-level = "fail"
final-status-level = "flaky"
